#!/bin/bash
#
# Triggers container image builds in GitHub Actions when the container registry
# is missing versions of the AWS CLI.

set -eo pipefail

# constants
PROGNAME="$(basename "$0")"
readonly PROGNAME

is_ge_version() {
    local version1="$1"
    local version2="$2"

    # uniq handles equal versions
    ! printf \
        '%s\n%s\n' \
        "${version1}" \
        "${version2}" \
        | sort --version-sort \
        | uniq --unique \
        | head --lines 1 \
        | grep --quiet "${version1}"
}

if ! [ "${GITHUB_ACTIONS}" ]; then
    printf '%s: %s\n' "${PROGNAME}" "must run in a GitHub Actions's workflow" >&2
    exit 1
fi

counter=1
paginate="$(\
    curl --silent "https://hub.docker.com/v2/namespaces/cavcrosby/repositories/aws-cli/tags?page=${counter}&&page_size=100" \
)"
while \
    ! printf \
        '%s\n' \
        "${paginate}" \
        | yq \
            --exit-status \
            --input-format "json" \
            '.message' \
            > "/dev/null" \
            2>&1; \
    do
        # shellcheck disable=SC2016 # yq exp does not need expansion
        dockerhub_tags="$(\
            yq eval-all \
                --input-format "json" \
                --output-format "json" \
                '. as $item ireduce ({}; . * $item)' \
                <(printf '%s\n' "${dockerhub_tags}") \
                <(printf '%s\n' "${paginate}") \
        )"

        : $(( counter++ ))
        paginate="$(\
            curl \
                --silent \
                "https://hub.docker.com/v2/namespaces/cavcrosby/repositories/aws-cli/tags?page=${counter}&&page_size=100" \
        )"
done

msg="$(printf '%s\n' "${paginate}" | yq --input-format "json" '.message')"
if [ "${msg}" != "httperror 404: object not found" ]; then
        printf \
            '%s: %s\n' \
            "${PROGNAME}" \
            "Docker Hub potentially returned a non-404 status message: ${msg}" \
            >&2

        exit 1
fi

gh_tags="$(\
    gh api \
        --paginate \
        "repos/aws/aws-cli/tags" \
        | yq --input-format "json" '[.[]] | flatten | .[].name' \
)"
for gh_tag in ${gh_tags}; do
    # version 2.33.12 is the starting/base version to build
    if is_ge_version "${gh_tag}" "2.33.12"; then
        if ! \
            printf \
            '%s\n' \
            "$(\
                printf \
                '%s\n' \
                "${dockerhub_tags}" \
                | yq '.results[] | .name' \
            )" \
            | grep --quiet "${gh_tag}";
        then
            if [ "${gh_tag}" = \
                "$(\
                    printf \
                        '%s\n' \
                        "${gh_tags}" \
                        | sort --version-sort \
                        | tail --lines 1 \
                )" \
            ]; then
                gh workflow run \
                    --repo "cavcrosby/aws-cli" \
                    --field version="${gh_tag}" \
                    --field latest="true" \
                    "build-images.yml"
            else
                gh workflow run \
                    --repo "cavcrosby/aws-cli" \
                    --field version="${gh_tag}" \
                    "build-images.yml"
            fi
        fi
    fi
done

exit 0
