#!/bin/bash
#
# Triggers container image builds in GitHub Actions when the container registry
# is missing versions of the AWS CLI.

set -eo pipefail

# constants
PROGNAME="$(basename "$0")"
readonly PROGNAME

is_ge_version() {
    local version1="$1"
    local version2="$2"

    # uniq handles equal versions
    ! printf \
        '%s\n%s\n' \
        "${version1}" \
        "${version2}" \
        | sort --version-sort \
        | uniq --unique \
        | head --lines 1 \
        | grep --quiet "${version1}"
}

if ! [ "${GITHUB_ACTIONS}" ]; then
    printf '%s: %s\n' "${PROGNAME}" "must run in a GitHub Actions's workflow" >&2
    exit 1
fi

dockerhub_tags="$(\
    curl \
        --silent \
        "https://hub.docker.com/v2/namespaces/cavcrosby/repositories/aws-cli/tags" \
)"

gh_tags="$(\
    gh api \
        --paginate \
        "repos/aws/aws-cli/tags" \
        | jq --raw-output '.[] | .name' \
)"

for gh_tag in ${gh_tags}; do
    if is_ge_version "${gh_tag}" "2.33.12"; then
        if ! printf '%s\n' "$(printf '%s\n' "${dockerhub_tags}" | jq --raw-output '.results[] | .name')" | grep --quiet "${gh_tag}"; then
            if [ "${gh_tag}" = "$(printf '%s\n' "${gh_tags}" | sort --version-sort | tail --lines 1)" ]; then
                gh workflow run \
                    --repo "cavcrosby/aws-cli" \
                    --field version="${gh_tag}" \
                    --field latest="true" \
                    "build-images.yml"
            else
                gh workflow run \
                    --repo "cavcrosby/aws-cli" \
                    --field version="${gh_tag}" \
                    "build-images.yml"
            fi
        fi
    fi
done

exit 0
